font_family      Lilex Nerd Font Mono Medium
font_size        14
bold_font        Lilex Nerd Font Mono Bold
italic_font      Lilex Nerd Font Mono Italic
bold_italic_font Lilex Nerd Font Mono Bold Italic

window_padding_width 5

scrollback_lines 10000
repaint_delay 10
input_delay 3
tab_bar_style powerline

remember_window_size  yes
initial_window_width  800 
initial_window_height 800

include ./nord.conf

